#!/bin/bash
cargo build --bin pruif --target armv7-unknown-linux-gnueabihf
cargo build --bin cli_runner --target armv7-unknown-linux-gnueabihf
scp ./target/armv7-unknown-linux-gnueabihf/debug/pruif debian@192.168.7.2:/home/debian/pruif
scp ./target/armv7-unknown-linux-gnueabihf/debug/cli_runner debian@192.168.7.2:/home/debian/cli_runner
# compile pru fw
cd ./target/pru
pasm -b ../../prufw/PRUDAC.p
pasm -b ../../prufw/PRUClock.p
# copy over to beagleboard
scp ./PRUDAC.bin debian@192.168.7.2:/home/debian/PRUDAC.bin
scp ./PRUClock.bin debian@192.168.7.2:/home/debian/PRUClock.bin

