#!/bin/bash
cargo build --bin pruif --target armv7-unknown-linux-gnueabihf
cargo build --bin cli_runner --target armv7-unknown-linux-gnueabihf
scp ./target/armv7-unknown-linux-gnueabihf/debug/pruif debian@beaglebone.local:/home/debian/pruif
scp ./target/armv7-unknown-linux-gnueabihf/debug/cli_runner debian@beaglebone.local:/home/debian/cli_runner
# compile pru fw
pasm -b ./prufw/PRUDAC.p
pasm -b ./prufw/PRUClock.p
# copy over to beagleboard
scp ./PRUDAC.bin debian@beaglebone.local:/home/debian/PRUDAC.bin
scp ./PRUClock.bin debian@beaglebone.local:/home/debian/PRUClock.bin

